name: "action-semantic-release"

inputs:
  branches:
    description: "Which branch to create the release from"
    required: false
    default: "main"
  flavour:
    description: "Which flavour of the release process to run"
    required: false
    default: "release"

runs:
  using: "composite"
  steps:
    - run: |
        yarn add -D \
          @semantic-release/commit-analyzer@8.0.1 \
          @semantic-release/release-notes-generator@9.0.1 \
          @semantic-release/changelog@5.0.1 \
          @semantic-release/github@7.2.0 \
          @semantic-release/npm@7.0.10 \
          conventional-changelog-conventionalcommits@4.5.0
      shell: bash
    - run: |
        npx semantic-release \
          --extends ${{ github.action_path }}/flavours/${{ inputs.flavour }}.js \
          --branches ${{ inputs.branches }} \
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ env.NPM_TOKEN }}
