name: "main"

on: push

jobs:
  main_release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: wearehanno/action-semantic-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for publishing a GitHub *Release*
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
